### PR TITLE
[DO NOT MERGE] Fixed Align dependencies in csproj

### PR DESCRIPTION
**Pull request by itniels**
#582: Align csproj with absolute paths.

### CODE REVIEW

**Comment by ffMathy** [comment]
Friendly reminder: the build fails 😊

**Comment by itniels** [comment]
Hmm It all builds just fine locally!
So either it is due to the absolute paths maybe not aligning with AppVeyors build servers.. or an AppVeyor problem with System.IO.Compression (i saw some posts)...

@ffMathy You are welcome to have a look at the logs in AppVeyor and give your opinion!
Since you have a bit more experience with it. 😃 

But i will keep trying ;)

**Comment by itniels** [comment]
I think this is an AppVeyor known conflict when using `System.IO.Compression` and have a project using `Netstandard 2.0` :-/

Feels like a hit'n'miss when just trying things!
Trying to decipher a possible workaround..

**Comment by ffMathy** [comment]
Hit and miss is fine! That's how it is. You should see my commit history sometimes 😂

Very nice work so far!

**Comment by ffMathy** [comment]
I approve of these changes - but we must fix the build failures before continuing.

**Comment by itniels** [comment]
Awesome 👍 
Still working on it @ffMathy :) So please do not merge yet! 😃

**Comment by itniels** [comment]
Sucks i cannot test this locally.. so sorry for all the pushes and AppVeyor builds :P

**Comment by itniels** [comment]
Closing this as an experimental branch..
I created a new one that gets me the same place, but with minimal changes :)

**Comment by ffMathy** [comment]
I like the way you work! Good idea!

**Pull request closed without merging**
