### PR TITLE
Fix 24

### LINKED ISSUE #24: Implement the "Copy as compressed folder" action

### PR DESCRIPTION
**Pull request by ffMathy**
@KoalaBear84 review? This should fix #24.

### CODE REVIEW

**Comment by KoalaBear84** [comment]
Great work, will test it. As I will move to another house I will be busy next couple of days/week I will have less time to help. Just so you know, just ask help, I will match it with me free time :)

**Comment by ffMathy** [comment]
Yeah sure, I already match this with my free time. Thanks for letting me know though, and contributing. As for formatting, great idea. I'll set up a ReSharper profile for all of this.

Also, no need to test. I have tested that the feature works. This was only a review, and thanks for that! :+1:

**Comment by ffMathy** [comment]
As for the Zip stuff, you are right that it is slow. In time, we can improve it. Right now, it's probably fine.

**Comment by KoalaBear84** [comment]
"Works on Mathias' machine" :P

**Pull request merged**
