### PR TITLE
Combine all whitespaces

### PR DESCRIPTION
**Pull request by KoalaBear84**
Use Regex to combine all type of whitespace to single space

### CODE REVIEW

**Comment by KoalaBear84** [comment]
Would be better in one commit. But just touching the basics of Git / Github for desktop. It looks like it now has a conflict. But I do not understand why, or have to resolve.

**Comment by ffMathy** [comment]
Thanks for your contribution! Helps a lot! Please keep it up if you get time.

Conflicts happen - that's okay. They are easy to solve for me. What you did helps a LOOOOT still.

**Comment by KoalaBear84** [comment]
Thanks. Will do!

**Comment by ffMathy** [comment]
Also, as for the "one commit". I make gazillions of commits myself, and often I even undo my commits later on. That doesn't matter! It's fine! :+1: 

Nobody looks back at the log anyway, so it is the code that changes that matters :smile:

**Comment by ffMathy** [comment]
Guys guys guys...

Okay, so the first rule is: No premature optimization! 

If we are talking nanoseconds, then why even bother? I would argue that even if the regular expression is slower (a few nanoseconds slower probably), then it is still worth it because it can be expressed in fewer amounts of code.

Also, the ordering of calls has just been fixed in a commit I made a few minutes after this one. So that's out of the way.

It gets even more interesting when you *actually* start looking at the performance instead of speculating about it.

So before we had something like this:

`while(something.Contains("  ")) something = something.Replace("  ", " ");`

This is really expensive! So a `Contains` call probably runs through the string (an array of characters) until it finds a match. In other words, it has a time complexity of `O(n)`. Then if that matches, we have a replace call, which probably *also* has to run through the array of characters, substitute as needed, and produce a new array of characters (a new string). Optimistically, it has a complexity of `O(n)` as well.

Adding this up (since we need to do a replace call for every space in the sequence), the final code has a time complexity of `O(n^2)`.

Let's think about this for a while.

So if we have the string `"hello<50 spaces>world"`, then this would require `n^2 = 50^2 = 2500` operations! That's crazy! Sure, not of big significance to modern CPUs (especially not if we follow @KoalaBear84's suggestion of enshortening it first, but that could also result in loss of data).

Now let's compare that with the simple regular expression Koala made. I would say that I could probably optimistically make a function that runs through every character in an array (a string) and substitutes every whitespace with nothing, with a time complexity of `O(n)`. Assuming that's what they have done, this means that @KoalaBear84's code is actually faster!

To make things even more interesting, the `Regex` class supports compilation (https://msdn.microsoft.com/en-us/library/8zbs0h2f(v=vs.110).aspx) which dramatically speeds up an expression.

I am implementing this right now, so that we can re-use a compiled regular expression (see upcoming commits if you want to see how it's done).

What I want to take away from this is: Optimize if you have a performance problem. If you don't, favor code readability and clean code over performance, until you reach a performance problem.

**Comment by ffMathy** [comment]
A last note: A profile can tell you concretely if you have an optimization. Often speculations are wrong, and lead to a waste of time. But you know this already I assume.

**Comment by ffMathy** [comment]
Oh, and @KoalaBear84? You'll be happy to know that Shapeshifter 5 uses WPF's "freezing" feature, resulting in a much faster user interface that also takes up less memory.

**Comment by KoalaBear84** [comment]
Finally some time to read. Ahh. I see. Had a hard time Googling for "WPF freezing" :P. But found out. If you don't need to modify resources you can call .Freeze() on them to avoid copying. Which you described as "memory leak", but maybe you meant "using too much memory" :)

Indeed. Only fix performance if it's a problem.

**Pull request merged**
