### PR TITLE
Fix #95 initial clipboard data

### LINKED ISSUE #95: Shapeshifter erases initial clipboard data
When starting up Shapeshifter, it doesn't respect the current clipboard data, and discards it.

### PR DESCRIPTION
**Pull request by dvitonis**
This makes `ClipboardUserInterfaceMediator` load what's in the clipboard when it's `Connect(...)`'ed.

### CODE REVIEW

**Comment by ffMathy** [comment]
This is a work of art! Great job. For some reason, it is failing to report build status for the first check. Can you push a whitespace and see if that helps?

Beautiful code. I will merge as soon as it reports a proper status.

**Comment by dvitonis** [comment]
Thanks. Just pushed, but didn't seem to do the trick.

**Comment by dvitonis** [comment]
It is most likely so because this branch is on my forked repository.

**Comment by ffMathy** [comment]
I got it merged now. Removed the "branch" check as it was redundant. Thanks for your contribution! I hope you keep them coming. I have added you as an official contributor. Your coding style matches very much with the expected quality level.

**Comment by dvitonis** [comment]
Sure, you can assign me to some appropriate tasks to gradually familiarize with the codebase.

**Comment by ffMathy** [comment]
I am more of a fan of letting people pick what issues they want to work on. If you find an issue that needs more explanation, just comment on it. If you start working on an issue, assign it with the label "working on it right now".

Thanks again.

**Pull request merged**
